## Building a GPT

Companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.

In [22]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!curl -L -o input.txt https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

  % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
                                 Dload  Upload  Total   Spent   Left   Speed

  0      0   0      0   0      0      0      0                              0
100  1.06M 100  1.06M   0      0  5.70M      0                              0
100  1.06M 100  1.06M   0      0  5.70M      0                              0
100  1.06M 100  1.06M   0      0  5.70M      0                              0


In [23]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

print(f"length of dataset in characters: {len(text):,}")
print(text[:1000])  # print the first 1000 characters to inspect

length of dataset in characters: 1,115,394
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hun

In [24]:
# Let's now get all the unique characters that occur in this text and encode them to integers, and vice versa
setoftext = set(text)
chars = sorted(list(set(text)))
vocab_size = len(chars)
print("all the unique characters:", ''.join(chars))
print("vocab size:", vocab_size)

all the unique characters: 
 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
vocab size: 65


In [25]:
!curl -L -o input.txt https://huggingface.co/datasets/Raziel1234/WebText-1/raw/main/corpus.txt

  % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
                                 Dload  Upload  Total   Spent   Left   Speed

  0      0   0      0   0      0      0      0                              0
100  1.94M 100  1.94M   0      0  2.98M      0                              0
100  1.94M 100  1.94M   0      0  2.98M      0                              0
100  1.94M 100  1.94M   0      0  2.98M      0                              0


In [26]:
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

print(f"length of dataset in characters: {len(text):,}")
print(text[:1000])  # print the first 1000 characters to inspect

length of dataset in characters: 2,026,239
OpenAI, Inc
is an American artificial intelligence (AI) organization founded in December 2015 and headquartered in San Francisco, California
It aims to develop "safe and beneficial" artificial general intelligence (AGI), which it defines as "highly autonomous systems that outperform humans at most economically valuable work".[6] As a leading organization in the ongoing AI boom,[7] OpenAI is known for the GPT family of large language models, the DALL-E series of text-to-image models, and a text-to-video model named Sora.[8][9] Its release of ChatGPT in November 2022 has been credited with catalyzing widespread interest in generative AI.
The organization has a complex corporate structure
As of April 2025, it is led by the non-profit OpenAI, Inc.,[1] registered in Delaware, and has multiple for-profit subsidiaries including OpenAI Holdings, LLC and OpenAI Global, LLC.[10] Microsoft has invested US$13 billion in OpenAI, and is entitled to 49% of O

In [27]:
sentence = 'Plates are used to serve food.' # P, l, a....

In [28]:
# apply set() on sentence
characterset = set(sentence)
print(characterset)

{'d', 'f', 't', '.', 'a', 'u', 'e', 'o', 'r', 's', 'l', 'P', 'v', ' '}


In [29]:
# cast characterset into a list
charactersetlisted = list(characterset)
firstcharoflist = charactersetlisted[0]
print(charactersetlisted)
print(firstcharoflist)

['d', 'f', 't', '.', 'a', 'u', 'e', 'o', 'r', 's', 'l', 'P', 'v', ' ']
d


In [30]:
#sort the characterlist sorted()
sortedkabom = sorted(charactersetlisted)
print(sortedkabom)

[' ', '.', 'P', 'a', 'd', 'e', 'f', 'l', 'o', 'r', 's', 't', 'u', 'v']


In [31]:
# ident the len of the short sentence the fuction is len()
lennnnny = len(sortedkabom)
print (lennnnny)


14


In [32]:
textlist = set(text)

In [33]:
textlist = sorted(list(set(text)))
lenned = len(textlist)
print ("".join(textlist))
print (lenned)


 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ £§ÁÅ×áâãçéíîïðóöüāăąČčĠħīłūɒɔəɛɡɣɪɬʁʃʌʒʔʕˈˌː̆αβθορςχְִֶַֹּ־ׁאבדהוילמןעצקרשתṯἙῖ ‎‑–—‘’“” ⁄⁡€∑−∣≈⊕ⓘ😊😐🦜
197


In [34]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ £§ÁÅ×áâãçéíîïðóöüāăąČčĠħīłūɒɔəɛɡɣɪɬʁʃʌʒʔʕˈˌː̆αβθορςχְִֶַֹּ־ׁאבדהוילמןעצקרשתṯἙῖ ‎‑–—‘’“” ⁄⁡€∑−∣≈⊕ⓘ😊😐🦜
197


###there are other ways to tokenize a text  

In [35]:
# create a mapping from characters to integers like tiktoken.get_encoding("gpt2")
stoi = { ch:i for i,ch in enumerate(textlist) }
itos = { i:ch for i,ch in enumerate(textlist) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii imasdasdasdasdasdad so stoopid"))
print(decode(encode("hii imasdasdasdasdasdad so stoopid")))

[73, 74, 74, 1, 74, 78, 66, 84, 69, 66, 84, 69, 66, 84, 69, 66, 84, 69, 66, 84, 69, 66, 69, 1, 84, 80, 1, 84, 85, 80, 80, 81, 74, 69]
hii imasdasdasdasdasdad so stoopid


In [36]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([2026239]) torch.int64
tensor([48, 81, 70, 79, 34, 42, 13,  1, 42, 79, 68,  0, 74, 84,  1, 66, 79,  1,
        34, 78, 70, 83, 74, 68, 66, 79,  1, 66, 83, 85, 74, 71, 74, 68, 74, 66,
        77,  1, 74, 79, 85, 70, 77, 77, 74, 72, 70, 79, 68, 70,  1,  9, 34, 42,
        10,  1, 80, 83, 72, 66, 79, 74, 91, 66, 85, 74, 80, 79,  1, 71, 80, 86,
        79, 69, 70, 69,  1, 74, 79,  1, 37, 70, 68, 70, 78, 67, 70, 83,  1, 19,
        17, 18, 22,  1, 66, 79, 69,  1, 73, 70, 66, 69, 82, 86, 66, 83, 85, 70,
        83, 70, 69,  1, 74, 79,  1, 52, 66, 79,  1, 39, 83, 66, 79, 68, 74, 84,
        68, 80, 13,  1, 36, 66, 77, 74, 71, 80, 83, 79, 74, 66,  0, 42, 85,  1,
        66, 74, 78, 84,  1, 85, 80,  1, 69, 70, 87, 70, 77, 80, 81,  1,  3, 84,
        66, 71, 70,  1, 66, 79, 69,  1, 67, 70, 79, 70, 71, 74, 68, 74, 66, 77,
         3,  1, 66, 83, 85, 74, 71, 74, 68, 74, 66, 77,  1, 72, 70, 79, 70, 83,
        66, 77,  1, 74, 79, 85, 70, 77, 77, 74, 72, 70, 79, 68, 70,  1,  9, 34,
      

In [37]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [38]:
block_size = 8
train_data[:block_size+1]

tensor([48, 81, 70, 79, 34, 42, 13,  1, 42])

In [39]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")
    

when input is tensor([48]) the target: 81
when input is tensor([48, 81]) the target: 70
when input is tensor([48, 81, 70]) the target: 79
when input is tensor([48, 81, 70, 79]) the target: 34
when input is tensor([48, 81, 70, 79, 34]) the target: 42
when input is tensor([48, 81, 70, 79, 34, 42]) the target: 13
when input is tensor([48, 81, 70, 79, 34, 42, 13]) the target: 1
when input is tensor([48, 81, 70, 79, 34, 42, 13,  1]) the target: 42


In [40]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[66, 90, 70, 83, 84,  1, 85, 73],
        [79, 70, 83,  1, 71, 86, 79, 68],
        [76,  1, 83, 70, 84, 70, 66, 83],
        [ 1, 85, 73, 66, 85,  1, 87, 74]])
targets:
torch.Size([4, 8])
tensor([[90, 70, 83, 84,  1, 85, 73, 66],
        [70, 83,  1, 71, 86, 79, 68, 85],
        [ 1, 83, 70, 84, 70, 66, 83, 68],
        [85, 73, 66, 85,  1, 87, 74, 80]])
----
when input is [66] the target: 90
when input is [66, 90] the target: 70
when input is [66, 90, 70] the target: 83
when input is [66, 90, 70, 83] the target: 84
when input is [66, 90, 70, 83, 84] the target: 1
when input is [66, 90, 70, 83, 84, 1] the target: 85
when input is [66, 90, 70, 83, 84, 1, 85] the target: 73
when input is [66, 90, 70, 83, 84, 1, 85, 73] the target: 66
when input is [79] the target: 70
when input is [79, 70] the target: 83
when input is [79, 70, 83] the target: 1
when input is [79, 70, 83, 1] the target: 71
when input is [79, 70, 83, 1, 71] the target: 86
when input is [

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguavgeModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 197])
tensor(6.1302, grad_fn=<NllLossBackward0>)

5הF5וü9}DLLṯיʌpF!kˌt‎YʔלYἙ@‘צˌJJūS’−-rW1ׁb”Eʁ-łɬ∣ⓘeā’3dOV ˌ{îαp×∑βɪÁç>FDâ‑C
â^,2£ɔα*|ֶֶ£ρצ]aʔ4ă-jʕ£ã


In [42]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)


In [43]:
batch_size = 32
for steps in range(1000000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


2.5535573959350586


In [44]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


PTheg d tios Eat in atmioff
Kerur; ogumy twheer canin furispecttorasiotons cast R
Tathansociche bantsce Clior on),[1994.[96tenghan the ore 254236][63.[2][7][6] ome GPT-lia t sinsitontirehar Pyl rorasiea w be, opte lll th AIntoumede.[127] aStske cthermphedy ithabordexthe f bunthmarux Senntoulekstmorondumeng g.] GPTh st sevenshen crele fther therure icudeppt Liter ONed, ther ande oftat s tis or wes.[695]
Itiedy /Inadeedia f bed ived Ras Wiquat.e iodedipucedermpasel the N on t wis ueve asizialver P
